### ISSUE TITLE
报错了请问这个怎么处理？

### ISSUE THREAD

**Issue by VXeffect** [THUDM/CodeGeeX4#6]
2024-07-05 18:43:44 - Invalid URL '': No scheme supplied. Perhaps you meant https://?
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\chainlit\utils.py", line 44, in wrapper
    return await user_function(**params_values)
  File "run.py", line 150, in main
    for part in stream:
  File "J:\Tools\CodeGeeX4\CodeGeeX4\repodemo\llm\api\codegeex4.py", line 21, in codegeex4
    response = requests.post(url, json=data, headers=headers, verify=False, stream=True)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?

按照公众号视频号教程，下载项目装了库 打开了chainlit ，run了之后，就这样了，模型也执行对应文件下载完毕

**Comment by VXeffect** [comment]
解决了

**Comment by xinpeng-zhang** [comment]
现在域名绑定，模型部署还有一些不太通用，后面我们会完善这个demo，然后开放更多的功能。感谢您的支持～！
